export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  REGISTER: 1,
  LOGIN: 3,
  MONSTER_ATTACK_BASE: 16,
  UPDATE_BASE_HP_NOTIFICATION: 17,
  GAME_OVER_NOTIFICATION: 18,
  GAME_END: 19
};
